#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	enum WINMODE { MODE_FULL, MODE_WIN };

	// Dynamic 컴포넌트 경우 매 프레임마다 갱신해야하는 컴포넌트 집단
	enum COMPONENTID { ID_DYNAMIC, ID_STATIC, ID_END };

	enum MATRIX_INFO {	INFO_RIGHT, INFO_UP, INFO_LOOK, INFO_POS, INFO_END };
	enum ROTATION { ROT_X, ROT_Y, ROT_Z, ROT_END };

	enum TEXTUREID { TEX_NORMAL, TEX_CUBE, TEX_END };

	enum RENDERID { RENDER_PRIORITY, RENDER_NONALPHA, RENDER_ALPHA, RENDER_UI, RENDER_END };

	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };
	enum MOUSEMOVESTATE {	DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };

	enum class COLLIDER_TYPE	{ COLLIDER_BOX, COLLIDER_CIRCLE, COLLIDER_END };
	enum class COMPONENT_TYPE	
	{ 
		COM_BUFFER,
		COM_TRANSFORM, 
		COM_BOX_COLLIDER, 
		COM_CIRCLE_COLLIDER, 
		COM_ANIMATOR,
		COM_TEXTURE,
		COM_END
	};

	enum class LAYER_TYPE { CAMERA, ENVIRONMENT, PLAYER, SPAWNER, MONSTER, EFFECT, UI, BACK_GROUND, LAYER_END };
	enum class SCENE_TYPE { LOADING, STAGE1, STAGE2, STAGE3, TOOL, SCENE_END };
	enum class OBJ_TYPE { OBJ_CAMERA, OBJ_ENVIRONMENT, OBJ_PLAYER, OBJ_SPAWNER, OBJ_MONSTER, OBJ_EFFECT, OBJ_UI, OBJ_BACKGROUND, OBJ_END };

}
#endif // Engine_Enum_h__
